name: check-tests
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: pip install pytest
      - run: make test
