name: check-tests
on: [push]
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
           pip install poetry
           make install
      - uses: paambaati/codeclimate-action@v2.7.5
        env: 
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageCommand: make test
