name: flake8-check
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: pip install flake8
      - run: make lint
